name_server: "8.8.8.8"
vmagent_version: "latest"
victoria_metrics_version: "latest"
grafana_version: "latest"
vmalert_version: "latest"
alertmanager_version: "latest"
node_exporter_version: "latest"
node_exporter_base_image: "prom/node-exporter"
elasticsearch_exporter_version: "v1.6.0"
elastic_exporter_base_image: "quay.io/prometheuscommunity/elasticsearch-exporter"
monitoring_user: "monitoring"
monitoring_password: "b5a24d12cfc0fdf696a09b9c3b0a4b59"
elastic_version: "8.11.1"
elastic_base_image: "docker.elastic.co/elasticsearch/elasticsearch"
kibana_version: "8.11.1"
kibana_base_image: "docker.elastic.co/kibana/kibana"
elastic_password: "fancyliqurebottle"
kibana_password: "tinyliqurebottle"
kibana_system_username: "kibana_system"
kibana_port: "5601"
disk_attach_path: "/dev/sdb"
snapshot_bucket_name: "<bucket_name>"
snapshot_bucket_access_key: "<access_key>"   #Put the value in double quotes
snapshot_bucket_secret_key: "<secret_key>"   #Put the value in double quotes
snapshot_s3_endpoint: "<s3_endpoint>"        #Put the value in double quotes
snapshot_registry_name: "<registry_name>"
snapshot_policy_name: "<policy_name>"
elasticsearch_cluster_name: "elasticsearch-production"
elasticsearch_base_directory: "/root/"
victoria_metrics_base_directory: "/root/"

