---
- name: check connectivity
  ping:
    data: alive

- name: Create a new primary partition
  community.general.parted:
    device: "{{ Disk_Attach_Path }}"
    number: 1
    state: present
    fs_type: ext4
    part_start: "0%"
    part_end: "100%"
    label: "gpt"

- name: Read device information (always use unit when probing)
  community.general.parted: device="{{ Disk_Attach_Path }}" unit=MiB
  register: disk_info

- name: Print out the disk info
  debug:
    var: disk_info
