---
- name: check connectivity
  ping:
    data: alive


- name: Extract the UUID of the additional disk
  shell:
    cmd: blkid -o full | grep "{{ Disk_Attach_Path }}1" | awk -F '"' '{print $2}'
  register: disk_uuid
  changed_when: false

- name: Mount up device by UUID
  ansible.posix.mount:
    path: /root/elastic_data/data
    src: "UUID={{ disk_uuid.stdout }}"
    fstype: ext4
    boot: true
    state: mounted

