---
- name: check connectivity
  ping:
    data: alive


- name: Extract the UUID of the additional disk
  shell:
    cmd: blkid -o full | grep "{{ DISK_ATTACH_PATH }}1" | awk -F '"' '{print $2}'
  register: disk_uuid
  changed_when: false

- name: Mount up device by UUID
  ansible.posix.mount:
    path: "{{ ELASTICSEARCH_BASE_DIRECTORY }}Elasticsearch/Elasticsearch_Data/"
    src: "UUID={{ disk_uuid.stdout }}"
    fstype: ext4
    boot: true
    state: mounted

