---
- name: check connectivity
  ping:
    data: alive


- name: Copy the certs to the nodes
  copy:
    src: "files/{{ item }}"
    dest: "{{ ELASTICSEARCH_BASE_DIRECTORY }}Elasticsearch/Config/Certs/"
  with_items:
    - "certs.zip"
    - "ca.zip"
    - "http_ca.crt"
    - "http.p12"
    - "transport.p12"
    - "instances.yaml"


- name: Unzip the certs
  unarchive:
    src: "{{ ELASTICSEARCH_BASE_DIRECTORY }}Elasticsearch/Config/Certs/{{ item }}"
    remote_src: true
    dest: "{{ ELASTICSEARCH_BASE_DIRECTORY }}Elasticsearch/Config/Certs/"
  with_items:
    - "certs.zip"
    - "ca.zip"


- name: Set the docker compose file for each elastic instance
  template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ ELASTICSEARCH_BASE_DIRECTORY }}Elasticsearch/Docker/docker-compose.yml"


- name: Set the config file for each elastic instance
  template:
    src: templates/elasticsearch.yml.j2
    dest: "{{ ELASTICSEARCH_BASE_DIRECTORY }}Elasticsearch/Config/elasticsearch.yml"

-
- name: Run the containers
  community.general.docker_compose:
    project_src: "{{ ELASTICSEARCH_BASE_DIRECTORY }}Elasticsearch/Docker/"
    pull: true
    recreate: never
    state: present
    restarted: false
    remove_orphans: no
    remove_volumes: false


