---
- name: General setup
  hosts: all
  become: true
  roles:
    - role: general
      tags: general-setup

- name: Setting up Elasticsearch cluster
  hosts: elasticsearch
  become: true
  roles:
    - role: elasticsearch_cluster
      tags: elasticsearch-setup

- name: Set up the monitoring stack
  hosts: monitoring
  become: true
  tasks:
    - name: Include monitoring roles
      include_role:
        name: "{{ item }}"
      loop:
        - $PWD/roles/victoria_metrics
      when: mode == 'monitoring'
