---
- name: General setup
  hosts: all
  become: true
  roles:
    - role: general
      tags: general-setup

- name: setting up Elasticsearch cluster
  hosts: elasticsearch
  become: true
  roles:
    - role: elasticsearch_cluster
      tags: elasticsearch-setup


- name: Set up the monitoring stack
  include_role:
    name: "{{ item }}"
  with_items:
    - $PWD/roles/victoria_metrics
  when: mode == 'monitoring'

