---
- name: setting up Elastic cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        #- $PWD/roles/OS_Tuning
        - $PWD/roles/Install_Docker


    - name: Tuning the nodes for elastic
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Elastic_Pre_Setup
      when: mode == 'elastic'



    - name: Install and Configure Elastic instances
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Cert_Generation_Elastic
      when: mode == 'elastic' and init_cluster == 'true'
