---
- name: setting up the basis for the cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars:
        file: "{{ playbook_dir }}/vars/{{ item }}"
      with_items:
        - "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/Install_Docker
        - $PWD/roles/Node_Exporter


    - name: Tuning the nodes for elastic
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Elastic_Pre_Setup
      when: mode == 'elastic'



    - name: Generate required certificates for elastic
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Cert_Generation_Elastic
      when: mode == 'elastic' and init_cluster == 'true'


    - name: Set up the monitoring stack
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Victoria_Metrics
      when: mode == 'monitoring'





- name: setting up the Elastic cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars:
        file: "{{ playbook_dir }}/vars/{{ item }}"
      with_items:
        - "all.yaml"

    - name: Setup and Configure Elastic instances
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Elastic_Setup_Dockerized
      when: mode == 'elastic'



    - name: Change password for kibana_system
      uri:
        url: "https://{{ ansible_host }}:9200/_security/user/kibana_system/_password"
        method: POST
        user: "elastic"
        password: "{{ elastic_password }}"
        body: '{"password": "{{ kibana_password }}"}'
        body_format: json
        validate_certs: false
        force_basic_auth: true
        status_code: 200
        headers:
          Content-Type: "application/json"
      when: mode == 'elastic' and init_cluster == 'true'


