---
- name: setting up the basis for the cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/Install_Docker
        - $PWD/roles/Node_Exporter


    - name: Tuning the nodes for elastic
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Elastic_Pre_Setup
      when: mode == 'elastic'



    - name: Generate required certificates for elastic
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Cert_Generation_Elastic
      when: mode == 'elastic' and init_cluster == 'true'

- name: setting up the Elastic cluster
  hosts: all
  become: true
  serial: 1
  tasks:
    - name: Include variables
      include_vars:
        file: "{{ playbook_dir }}/vars/{{ item }}"
      with_items:
        - "all.yaml"

    - name: Setup and Configure Elastic instances
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Elastic_Setup_Dockerized
      when: mode == 'elastic'

