---
- name: check connectivity
  ping:
    data: alive


- name: Create the required directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  with_items:
    - /root/elastic_certs/
    - /root/elastic_certs/config/
    - /root/elastic_certs/config/certs



- name: Pull the elastic image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:{{ elastic_version }}
    source: pull


- name: Copy /etc/hosts file
  template:
    src: files/instances.yaml
    dest: /root/elastic_certs/config/certs/instances.yaml
    owner: root
    group: root
    mode: '0644'



- name: Run the elastic container for cert generation
  docker_container:
    name: "elastic_cert_generator"
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elastic_version }}
    restart_policy: no
    state: started
    privileged: true
    network_mode: host
    volumes:
      - /root/elastic_certs/config/certs/instances.yaml:/usr/share/elasticsearch/instances.yaml

- name: Sleep for 30s so the elastic would be ready
  pause:
    seconds: 30
    prompt: Waiting for elastic to be ready for requsts


- name: Generate the ca
  community.docker.docker_container_exec:
    container: "elastic_cert_generator"
    command: bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip
  register: result_generate_ca


- name: Extract the ca
  community.docker.docker_container_exec:
    container: "elastic_cert_generator"
    command: unzip config/certs/ca.zip -d config/certs
  register: result_extract


- name: Generate the certificates
  community.docker.docker_container_exec:
    container: "elastic_cert_generator"
    command: bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in /usr/share/elasticsearch/instances.yaml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key
  register: result_generate


- name: Extract the certificates
  community.docker.docker_container_exec:
    container: "elastic_cert_generator"
    command: unzip config/certs/certs.zip -d config/certs
  register: result_extract_certificate


- name: Extract the certificates
  shell:
    cmd: docker cp elastic_cert_generator:/usr/share/elasticsearch/config/certs /root/elastic_certs/config/

  register: result


- name: Print out the result of the init command
  debug:
    var: result


- name: Fetch the certs
  fetch:
    src: "{{ item }}"
    flat: true
    dest: $PWD/roles/Elastic_Setup_Dockerized/files/
  with_items:
    - "/root/elastic_certs/config/certs/certs.zip"
    - "/root/elastic_certs/config/certs/ca.zip"
    - "/root/elastic_certs/config/certs/http_ca.crt"
    - "/root/elastic_certs/config/certs/http.p12"
    - "/root/elastic_certs/config/certs/transport.p12"
    - "/root/elastic_certs/config/certs/instances.yaml"
  register: result

- name: print the result
  debug:
    var: result





