---
- name: check connectivity
  ping:
    data: alive


- name: Create the required directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  with_items:
    - /root/elastic_data/
    - /root/elastic_data/data


- name: Extract the UUID of the additional disk
  shell:
    cmd: blkid -o full | grep "{{ Disk_Attach_Path }}" | awk -F '"' '{print $2}'
  register: disk_uuid
  changed_when: false

- name: Mount up device by UUID
  ansible.posix.mount:
    path: /root/elastic_data/data
    src: "UUID={{ disk_uuid.stdout }}"
    fstype: ext4
    boot: true
    state: mounted

